### ISSUE TITLE
Access to Android/data on external sdcard

### ISSUE THREAD

**Issue by giving-sesame** [Magisk-Modules-Alt-Repo/NoStorageRestrict#1]
Hi. Should this module provide free access to Android/data on external sdcard? I have Android 11. Mixplorer and built-in Files cannot access this folder even with module activated.

The only bypass is via /mnt/media_rw/

**Comment by DanGLVK** [comment]
> Hi. Should this module provide free access to Android/data on external sdcard? I have Android 11. Mixplorer and built-in Files cannot access this folder even with module activated.
> 
> The only bypass is via /mnt/media_rw/

The module only bypasses the restriction for selecting folders from withing apps, it doesn't allow free access to the Android/data folder, i will look into the possibility of that however and update you on the matter

**Comment by DanGLVK** [comment]
> Hi. Should this module provide free access to Android/data on external sdcard? I have Android 11. Mixplorer and built-in Files cannot access this folder even with module activated.
> 
> The only bypass is via /mnt/media_rw/

Alright, after i've looked into it, enabling free access to those folders doesn't seem possible with just a Magisk module unfortunately

**Comment by DanGLVK** [comment]
> Hi. Should this module provide free access to Android/data on external sdcard? I have Android 11. Mixplorer and built-in Files cannot access this folder even with module activated.
> 
> The only bypass is via /mnt/media_rw/

Ok, seems it might be possible to do that with the stock files app, tho just to be safe I'll need you to send me the APK from your device

**Comment by giving-sesame** [comment]
Thank you! I'm sorry I misunderstood the purpose of your module. It would be great if you could amend the Files in the due way. Please see the file attached.

[DocumentsUI.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/8403996/DocumentsUI.zip)

**Comment by DanGLES3** [comment]
> 

What exacr folder does it come from? I'mma make you a module for a modded files (can't guarantee it will work tho)

**Comment by DanGLVK** [comment]
> Thank you! I'm sorry I misunderstood the purpose of your module. It would be great if you could amend the Files in the due way. Please see the file attached.
> 
> [DocumentsUI.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/8403996/DocumentsUI.zip)

What exacr folder does it come from? I'mma make you a module for a modded files (can't guarantee it will work tho)

**Comment by giving-sesame** [comment]
/system/priv-app/DocumentsUI/DocumentsUI.apk

**Comment by DanGLVK** [comment]
> /system/priv-app/DocumentsUI/DocumentsUI.apk



> /system/priv-app/DocumentsUI/DocumentsUI.apk

[NoStorageRestrict-main.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/8404680/NoStorageRestrict-main.zip)

See if this works for you

**Comment by giving-sesame** [comment]
Does not work, unfortunately. I'm afraid it is incurable. Thank you for your help!
