### ISSUE TITLE
Android 13 Compatibility

### ISSUE THREAD

**Issue by shivamkadbhane** [Magisk-Modules-Alt-Repo/NoStorageRestrict#10]
I saw in an Android 13 changelog post that apparently Google has fixed the SAF loophole in A13. So will this module still work?
The post I mentioned - https://blog.esper.io/android-dessert-bites-28-file-manager-loophole-closed-73891524/

**Comment by DanGLVK** [comment]
> I saw in an Android 13 changelog post that apparently Google has fixed the SAF loophole in A13. So will this module still work? The post I mentioned - https://blog.esper.io/android-dessert-bites-28-file-manager-loophole-closed-73891524/

It should, the way Google fixed the loophole was just to add the /data and /obb directories to the shouldblockfromtree method (alongside Android, and the root of internal/external storage which were there previously)

My module uses a patched APK with that method always returning false, so no directories get blocked from SAF

**Comment by shivamkadbhane** [comment]
Gotcha. Thanks :)
