### ISSUE TITLE
unzip error (not an issue maybe)

### ISSUE THREAD

**Issue by Martinligabue** [Magisk-Modules-Alt-Repo/NoStorageRestrict#11]
hi, I downloaded the repo as zip and tried to install but it fails with "unzip error"

**Comment by DanGLVK** [comment]
> hi, I downloaded the repo as zip and tried to install but it fails with "unzip error"

You don't download repos as zips as GitHub zips the folder and not just the contents inside it (which results in an invalid module), to properly download modules use something like this

https://github.com/Fox2Code/FoxMagiskModuleManager/releases

**Comment by Martinligabue** [comment]
Thanks, sorry for the issue
