### ISSUE TITLE
v4 crashes

### ISSUE THREAD

**Issue by sn-o-w** [Magisk-Modules-Alt-Repo/NoStorageRestrict#13]
Hi there,

There's something wrong with latest version. I get an error mesage like "External storage keeps crashing".

It used to work well on my device with v2 and v3. 🤔

Device: Nexus 5
OS: LineageOS 18.1 (Android 11)

**Comment by DanGLVK** [comment]
> Hi there,
> 
> There's something wrong with latest version. I get an error mesage like "External storage keeps crashing".
> 
> It used to work well on my device with v2 and v3. 🤔
> 
> Device: Nexus 5 OS: LineageOS 18.1 (Android 11)

I'm aware of the issue and working on a fix asap

**Comment by DanGLVK** [comment]
> Hi there,
> 
> There's something wrong with latest version. I get an error mesage like "External storage keeps crashing".
> 
> It used to work well on my device with v2 and v3. 🤔
> 
> Device: Nexus 5 OS: LineageOS 18.1 (Android 11)

Alright, latest update I've just released should fix the issue, tested on my device this time just to be safe

**Comment by sn-o-w** [comment]
Yup, v5 fixes the issue. 👍
