### ISSUE TITLE
extSD

### ISSUE THREAD

**Issue by diedbug2002** [Magisk-Modules-Alt-Repo/NoStorageRestrict#14]
Hi

Both V4&V5 cant see and select ext-SD, please check

V3 work normal

Device：Samsung S9+
OS：Noble Rom 2.6.1（Android 12）

**Comment by DanGLVK** [comment]
> Hi
> 
> Both V4&V5 cant see and select ext-SD, please check
> 
> V3 work normal
> 
> Device：Samsung S9+ OS：Noble Rom 2.6.1（Android 12）

Alright, do me a favor, uninstall/disable the module, reboot and send me your device's external storage provider APK 

I don't really have an 12 device to test, tho oddly the method I've used on v5 works just fine for me on 11 when it comes to the sdcard 

Don't forget to send the APK

**Comment by diedbug2002** [comment]
APK here

[APK](https://drive.google.com/file/d/1burLugKz_tL1_hzj16Wtl1ucZv69ckIu/view?usp=sharing)

**Comment by diedbug2002** [comment]
APK here

[ExternalStorageProvider.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/9639871/ExternalStorageProvider.zip)

**Comment by DanGLVK** [comment]
> APK here
> 
> [ExternalStorageProvider.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/9639871/ExternalStorageProvider.zip)

[NoStorageRestrict-main (1).zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/9639875/NoStorageRestrict-main.1.zip)

Try this

**Comment by diedbug2002** [comment]
same problem :'(

can only see internel SD

**Comment by DanGLVK** [comment]
> same problem :'(
> 
> can only see internel SD

Alright, i found an issue with my module script, try redownloading it through fox module manager, it should work now 

Issue was some broken Android 12.0 detection

**Comment by diedbug2002** [comment]
redownloaded but got same problem

**Comment by DanGLVK** [comment]
> redownloaded but got same problem

Sorry for all the issues but all I need is one last thing, go to the module's folder in
/data/adb/modules/nostoragerestrict

Look around the folders there and see if you find an APK there

**Comment by diedbug2002** [comment]
[ExternalStorageProvider.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/9639970/ExternalStorageProvider.zip)

yep this one

**Comment by DanGLVK** [comment]
> [ExternalStorageProvider.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/9639970/ExternalStorageProvider.zip)
> 
> yep this one

[NoStorageRestrict-main (r).zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/9639978/NoStorageRestrict-main.r.zip)

Last zip of tonight, hopefully this works, I've rewritten the APK in the same way I've did on v3

If you want an advice, i personally recommend the Xposed module over the Magisk module, replacing the whole externalstorageprovider APK is grounds for issues 

I'll still try to keep the Magisk module updated and working, it's just that i can't guarantee it'll always work as intended specially on Android versions i have no access to

**Comment by diedbug2002** [comment]
> 

this one work CHEERS

**Comment by DanGLVK** [comment]
> > 
> 
> this one work CHEERS

Cool

**Comment by DanGLVK** [comment]
> > 
> 
> this one work CHEERS

Thanks for testing and sorry for the issues
