### ISSUE TITLE
Module does not work on Android 13

### ISSUE THREAD

**Issue by WitheringWyvern** [Magisk-Modules-Alt-Repo/NoStorageRestrict#15]
Files app crashes as soon as it opens.

**Comment by DanGLVK** [comment]
> Files app crashes as soon as it opens.

For the time being I'd suggest using the xposed version if that happens, due to reasons currently unknown to me, the patched APKs work inconsistently across devices/ROMs

**Comment by WitheringWyvern** [comment]
Hmm, the Xposed version seems to not work as well, and when using it, Mixplorer doesn't work while it was able to with the apk version.

**Comment by WitheringWyvern** [comment]
To anyone wondering, I was able to bypass this by going to /data/media/0/Android using MiXplorer

**Comment by DanGLVK** [comment]
> To anyone wondering, I was able to bypass this by going to /data/media/0/Android using MiXplorer

I'll have to investigate, could you send me your device's external storage provider APK? Odd that it didn't work considering it did so for most other users

**Comment by WitheringWyvern** [comment]
Wait which app is the external storage provider? The built in Files app?

**Comment by DanGLVK** [comment]
> Wait which app is the external storage provider? The built in Files app?

The system app named external storage provider, it's not the files app

**Comment by WitheringWyvern** [comment]
[com.android.externalstorage_v33.apk.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/10233662/com.android.externalstorage_v33.apk.zip)

**Comment by DanGLVK** [comment]
> [com.android.externalstorage_v33.apk.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/10233662/com.android.externalstorage_v33.apk.zip)

I'm a bit in a hurry since it's late rn but I'll send you the zip to test it
[NoStorageRestrict-main.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/10233719/NoStorageRestrict-main.zip)

**Comment by WitheringWyvern** [comment]
It still seems to not work, file managers can't access the data folder and obb folder contents show as empty

**Comment by DanGLVK** [comment]
> It still seems to not work, file managers can't access the data folder and obb folder contents show as empty

That's not what this module is about however, I think you might have misunderstood what it's about (it's for allowing the granting of access to folders where Android would normally prompt you to pick another such as the download folder)

Having third party file managers be restricted from accessing the Android folder is an restriction deeply rooted into the system that's not easily removable

**Comment by WitheringWyvern** [comment]
Ah, I see
