### ISSUE TITLE
Incompatible with Android 14

### ISSUE THREAD

**Issue by adamf663** [Magisk-Modules-Alt-Repo/NoStorageRestrict#16]
NoStorageRestrict causes the file chooser to hang at recents with no files shown.  I've seen this in many apps such as call recorder, or the smart audiobook player's root library select.

**Comment by DanGLVK** [comment]
> NoStorageRestrict causes the file chooser to hang at recents with no files shown. I've seen this in many apps such as call recorder, or the smart audiobook player's root library select.

I recommend using the Xposed version, the Magisk version is problematic and hard for me to fix not to mention it wasn't updated for Android 14

**Comment by adamf663** [comment]
Magisk  was installed for second user.
