### ISSUE TITLE
Issues since March 2024 security patch

### ISSUE THREAD

**Issue by Adelheid7722** [Magisk-Modules-Alt-Repo/NoStorageRestrict#17]
Sadly, when installing this module on ROMs with March 2024 or newer security patches, file manager stops showing my storage files, even external ones and anything that needs it stops working

**Comment by DanGLES3** [comment]
The Magisk version is essentially deprecated, only the Xposed version is maintained

**Comment by Adelheid7722** [comment]
Thank you for your answer, and for this module, i will check for Xposed/LSposed module.

**Comment by palexdev** [comment]
@DanGLES3 since I can't use LSPosed because it is detected by some apps that will by consequence crash on start.
Can you at least tell me how did you modify/compile the ExternalStorageProvider apk?

To be more clear, since it is not a simple app, and it's part of framework/base/packages, did you simply modified the apk file directly (smali?) or did you modify the source code?

**Comment by DanGLES3** [comment]
> @DanGLES3 since I can't use LSPosed because it is detected by some apps that will by consequence crash on start. Can you at least tell me how did you modify/compile the ExternalStorageProvider apk?
> 
> To be more clear, since it is not a simple app, and it's part of framework/base/packages, did you simply modify the apk file directly (smali?) or did you modify the source code?

Issue is modding the app of stock/signed ROM's without Lsposed isn't easy because the external storage provider app normally needs to be signed with the platform key to work

**Comment by palexdev** [comment]
> > @DanGLES3 since I can't use LSPosed because it is detected by some apps that will by consequence crash on start. Can you at least tell me how did you modify/compile the ExternalStorageProvider apk?
> > To be more clear, since it is not a simple app, and it's part of framework/base/packages, did you simply modify the apk file directly (smali?) or did you modify the source code?
> 
> Issue is modding the app of stock/signed ROM's without Lsposed isn't easy because the external storage provider app normally needs to be signed with the platform key to work

Hmm, I thought so
There are two other ways then:
1) Making a patch for Lucky Patcher but I have no idea how it works
2) Modifying the source code directly when building a ROM, which is a bit tedious though

**Comment by DanGLES3** [comment]
> > > @DanGLES3 since I can't use LSPosed because it is detected by some apps that will by consequence crash on start. Can you at least tell me how did you modify/compile the ExternalStorageProvider apk?
> > > To be more clear, since it is not a simple app, and it's part of framework/base/packages, did you simply modify the apk file directly (smali?) or did you modify the source code?
> > 
> > 
> > Issue is modding the app of stock/signed ROM's without Lsposed isn't easy because the external storage provider app normally needs to be signed with the platform key to work
> 
> Hmm, I thought so There are two other ways then:
> 
> 1. Making a patch for Lucky Patcher but I have no idea how it works
> 2. Modifying the source code directly when building a ROM, which is a bit tedious though

Me neither, tho I think Lucky Patcher can use the dex files from already modded apps to create a Dex file onto the system app

So in theory I can mod the apk for you and you import its ODEX using Lucky Patcher

**Comment by palexdev** [comment]
It does operate on ODEX files indeed, but I don't know if such import function exists

**Comment by DanGLES3** [comment]
> It does operate on ODEX files indeed, but I don't know if such import function exists

Iirc it does, when browsing on lucky patcher's file manager to an apk (of an already installed app) it shows the option to import the odex of that apk

**Comment by palexdev** [comment]
Although to be precise as also described in the following documentation 
![Screenshot_20240727-014744](https://github.com/user-attachments/assets/5d277d5f-8bfb-4420-97c6-58cb96fd34be)

It operates on .dex files to generate patched .odex files

As soon as I have enough free time on my schedule I'm going to try the IDA method, see if it's feasible 
It would be my first reverse engineering work 😅

**Comment by DanGLES3** [comment]
> Although to be precise as also described in the following documentation ![Screenshot_20240727-014744](https://private-user-images.githubusercontent.com/16880178/352685102-5d277d5f-8bfb-4420-97c6-58cb96fd34be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMzg5ODQsIm5iZiI6MTcyMjAzODY4NCwicGF0aCI6Ii8xNjg4MDE3OC8zNTI2ODUxMDItNWQyNzdkNWYtOGJmYi00NDIwLTk3YzYtNThjYjk2ZmQzNGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDAwMDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NTcyNDA4Mzg0MzQwYjMzODE2ZTRjODMyM2ZhZTg4YzQ4ZGQ2ZmUzZGYzYzM2YTA3MWQzMTQyYmIxNGFiNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uePYSg70SBbejBsn1JurShKa9pryORoipTGqiTbFRww)
> 
> It operates on .dex files to generate patched .odex files
> 
> As soon as I have enough free time on my schedule I'm going to try the IDA method, see if it's feasible It would be my first reverse engineering work 😅

The names of the method you need to patch can be found in the source code of this module, it's just setting a value to always be true

**Comment by palexdev** [comment]
> Although to be precise as also described in the following documentation ![Screenshot_20240727-014744](https://private-user-images.githubusercontent.com/16880178/352685102-5d277d5f-8bfb-4420-97c6-58cb96fd34be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9. 
> The names of the method you need to patch can be found in the source code of this module, it's just setting a value to always be true 

Did you know it changed again to `shouldBlockDirectoryFromTree`?

![Screenshot_20240727-102117.png](https://github.com/user-attachments/assets/71db93a6-5800-4a65-975a-35de214bc64e)

**Comment by DanGLES3** [comment]
> > Although to be precise as also described in the following documentation ![Screenshot_20240727-014744](https://private-user-images.githubusercontent.com/16880178/352685102-5d277d5f-8bfb-4420-97c6-58cb96fd34be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
> > The names of the method you need to patch can be found in the source code of this module, it's just setting a value to always be true
> 
> Did you know it changed again to `shouldBlockDirectoryFromTree`?
> 
> ![Screenshot_20240727-102117.png](https://private-user-images.githubusercontent.com/16880178/352709999-71db93a6-5800-4a65-975a-35de214bc64e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjkxMzksIm5iZiI6MTcyMjA2ODgzOSwicGF0aCI6Ii8xNjg4MDE3OC8zNTI3MDk5OTktNzFkYjkzYTYtNTgwMC00YTY1LTk3NWEtMzVkZTIxNGJjNjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA4MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MjZjODEzMWQ2MDg3NjFkYjgyMjU5MjE4MjFiNWEyNDQ5MDc4YTJmYWZjMjVjOWZmYzNlNjM3NGJkN2M0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.spRJIv1FivezGioClQoQFGX-6Z3BG5az-D6cBamt32g)

Yeah, my code accommodate both the old and new method names

**Comment by palexdev** [comment]
I tried again and again with LuckyPatchers but I could not get it to work, even though I'm pretty sure my patch is correct.

So, I opted for the other option, integrating the features directly in the ROM.
[android_patches](https://github.com/palexdev/android_patches)

**Comment by DanGLES3** [comment]
> I tried again and again with LuckyPatchers but I could not get it to work, even though I'm pretty sure my patch is correct.
> 
> So, I opted for the other option, integrating the features directly in the ROM. [android_patches](https://github.com/palexdev/android_patches)

Neat, BTW what apps do you have issues when Lsposed is installed? Mind giving a link?

**Comment by palexdev** [comment]
> > I tried again and again with LuckyPatchers but I could not get it to work, even though I'm pretty sure my patch is correct.
> > So, I opted for the other option, integrating the features directly in the ROM. [android_patches](https://github.com/palexdev/android_patches)
> 
> Neat, BTW what apps do you have issues when Lsposed is installed? Mind giving a link?

[ClashRoyale](https://play.google.com/store/search?q=clash+royale&c=apps) straight up crashes
I tried any LSPosed version in existence. Last I tried was LSPosedN which now has disappeared from GitHub

**Comment by palexdev** [comment]
> > > > I tried again and again with LuckyPatchers but I could not get it to work, even though I'm pretty sure my patch is correct.
> > > > So, I opted for the other option, integrating the features directly in the ROM. [android_patches](https://github.com/palexdev/android_patches)
> > > 
> > > 
> > > Neat, BTW what apps do you have issues when Lsposed is installed? Mind giving a link?
> > 
> > 
> > [ClashRoyale](https://play.google.com/store/search?q=clash+royale&c=apps) straight up crashes I tried any LSPosed version in existence. Last I tried was LSPosedN which now has disappeared from GitHub
> 
> When does it crash? With this build I've made based on 5ec1cff's code it started just fine [LSPosed-npm-v1.0-4201-zygisk-release (2).zip](https://github.com/user-attachments/files/16445662/LSPosed-npm-v1.0-4201-zygisk-release.2.zip)

It still crashes on my device, and the [log](https://paste.crdroid.net/dg4Bws) in not even helpful

**Comment by DanGLES3** [comment]
> > > > > I tried again and again with LuckyPatchers but I could not get it to work, even though I'm pretty sure my patch is correct.
> > > > > So, I opted for the other option, integrating the features directly in the ROM. [android_patches](https://github.com/palexdev/android_patches)
> > > > 
> > > > 
> > > > Neat, BTW what apps do you have issues when Lsposed is installed? Mind giving a link?
> > > 
> > > 
> > > [ClashRoyale](https://play.google.com/store/search?q=clash+royale&c=apps) straight up crashes I tried any LSPosed version in existence. Last I tried was LSPosedN which now has disappeared from GitHub
> > 
> > 
> > When does it crash? With this build I've made based on 5ec1cff's code it started just fine [LSPosed-npm-v1.0-4201-zygisk-release (2).zip](https://github.com/user-attachments/files/16445662/LSPosed-npm-v1.0-4201-zygisk-release.2.zip)
> 
> It still crashes right after the logo on my device, and the [log](https://paste.crdroid.net/dg4Bws) is not even helpful

Hmm, what Zygisk do you use?

**Comment by palexdev** [comment]
![Screenshot_20240731-204152_KernelSU.png](https://github.com/user-attachments/assets/c2f19118-f0b3-40d4-b9ad-5d734336635e)

**Comment by palexdev** [comment]
![Screenshot_20240731-204152_KernelSU~2.png](https://github.com/user-attachments/assets/f756c7b5-93f7-46d5-9697-d557e0fd134f)

**Comment by DanGLES3** [comment]
> ![Screenshot_20240731-204152_KernelSU~2.png](https://private-user-images.githubusercontent.com/16880178/353953813-f756c7b5-93f7-46d5-9697-d557e0fd134f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTE3ODYsIm5iZiI6MTcyMjQ1MTQ4NiwicGF0aCI6Ii8xNjg4MDE3OC8zNTM5NTM4MTMtZjc1NmM3YjUtOTNmNy00NmQ1LTk2OTctZDU1N2UwZmQxMzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE4NDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYjc2OWRiMzk1Y2I4NGQ2NmMzYmJlYjljNzkzYTM4ODFlYTBkYjAwYzQzZDE5YzYwMjU2ZDQzOTJiYjdiNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GMVA2AWlou5GuYCyTFgAcWjKbjsBjMmbsPvgNHyYUk0)

I see, KernelSU by itself doesn't hide Lsposed's mounts, you need the aid of something like Shamiko or Zygisk Assistant

**Comment by palexdev** [comment]
Success?

I just opened Zygisk Next interface and enable the 'Enforce Deny List' option
I didn't know it lol

The game now starts

**Comment by DanGLES3** [comment]
> Success?
> 
> I just opened Zygisk Next interface and enable the 'Enforce Deny List' option I didn't know it lol
> 
> The game now starts

Bruh, there you go, problem solved lol

**Comment by palexdev** [comment]
I never enabled that option before and it always worked just fine though.

Anyways, thanks you very much for the support!  😁
