### ISSUE TITLE
Android 14

### ISSUE THREAD

**Issue by Arkl1ne** [Magisk-Modules-Alt-Repo/NoStorageRestrict#18]
It's work in android 14?

**Comment by DanGLVK** [comment]
Yes, it should

**Comment by ghost** [comment]
No, it doesn’t work for me, I have Android 14 Hyper OS 1.3.0 and I just have nothing, it doesn’t show any button to allow access or folders

**Comment by DanGLVK** [comment]
> No, it doesn’t work for me, I have Android 14 Hyper OS 1.3.0 and I just have nothing, it doesn’t show any button to allow access or folders

Oh, you need to use the Xposed version, the Magisk version is no longer being maintained as it has issues with stock ROMs due to signature mismatch or code verification errors

Also my previous response was a mistake, I thought I was replying to an issue of my other module, I'm sorry

**Comment by ghost** [comment]
But Xposed does not support Android 14 or maybe you know where to download this version and can share?

**Comment by DanGLVK** [comment]
> But Xposed does not support Android 14 or maybe you know where to download this version and can share?

Some people reported this to work on Android 14 QPR2

https://github.com/mywalkb/LSPosed_mod/releases

**Comment by ghost** [comment]
Thanks, I already figured it out, everything works

**Comment by eku** [comment]
Does not work with Android 14 (LineageOS 21):

```
 1314  2189 I ActivityManager: Start proc 31844:com.android.externalstorage/u0a100 for restart com.android.externalstorage
 1314  2188 I ActivityManager: Skip zero pid ANR, process=com.android.externalstorage
31844 31844 I (6)[31844:externalstorage][20240421_16:43:29.731651]@6 binder: 31844:31844 ioctl 40046210 7ffb3c8340 returned -22
31844 31844 E AndroidRuntime: FATAL EXCEPTION: main
31844 31844 E AndroidRuntime: Process: com.android.externalstorage, PID: 31844
31844 31844 E AndroidRuntime: java.lang.LinkageError: Method android.database.Cursor com.android.externalstorage.ExternalStorageProvider.queryChildDocumentsForManage(java.lang.String, java.lang.String[], java.lang.String) overrides final method in class Lcom/android/internal/content/FileSystemProvider; (declaration of 'com.android.externalstorage.ExternalStorageProvider' appears in /system/priv-app/ExternalStorageProvider/ExternalStorageProvider.apk)
31844 31844 E AndroidRuntime:        at java.lang.VMClassLoader.findLoadedClass(Native Method)
31844 31844 E AndroidRuntime:        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
31844 31844 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
31844 31844 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
31844 31844 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
31844 31844 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7825)
31844 31844 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7347)
31844 31844 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7042)
31844 31844 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
31844 31844 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
31844 31844 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
31844 31844 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
31844 31844 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
31844 31844 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8248)
31844 31844 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
31844 31844 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
31844 31844 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
 1314 11668 W ActivityManager: Process com.android.externalstorage has crashed too many times, killing! Reason: crashed quickly
 1314 11668 I ActivityManager: Killing 31844:com.android.externalstorage/u0a100 (adj 0): crash

```

**Comment by DanGLVK** [comment]
> Does not work with Android 14 (LineageOS 21):
> 
> ```
>  1314  2189 I ActivityManager: Start proc 31844:com.android.externalstorage/u0a100 for restart com.android.externalstorage
>  1314  2188 I ActivityManager: Skip zero pid ANR, process=com.android.externalstorage
> 31844 31844 I (6)[31844:externalstorage][20240421_16:43:29.731651]@6 binder: 31844:31844 ioctl 40046210 7ffb3c8340 returned -22
> 31844 31844 E AndroidRuntime: FATAL EXCEPTION: main
> 31844 31844 E AndroidRuntime: Process: com.android.externalstorage, PID: 31844
> 31844 31844 E AndroidRuntime: java.lang.LinkageError: Method android.database.Cursor com.android.externalstorage.ExternalStorageProvider.queryChildDocumentsForManage(java.lang.String, java.lang.String[], java.lang.String) overrides final method in class Lcom/android/internal/content/FileSystemProvider; (declaration of 'com.android.externalstorage.ExternalStorageProvider' appears in /system/priv-app/ExternalStorageProvider/ExternalStorageProvider.apk)
> 31844 31844 E AndroidRuntime:        at java.lang.VMClassLoader.findLoadedClass(Native Method)
> 31844 31844 E AndroidRuntime:        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
> 31844 31844 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
> 31844 31844 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 31844 31844 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
> 31844 31844 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7825)
> 31844 31844 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7347)
> 31844 31844 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7042)
> 31844 31844 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
> 31844 31844 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
> 31844 31844 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
> 31844 31844 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
> 31844 31844 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
> 31844 31844 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8248)
> 31844 31844 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 31844 31844 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> 31844 31844 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
>  1314 11668 W ActivityManager: Process com.android.externalstorage has crashed too many times, killing! Reason: crashed quickly
>  1314 11668 I ActivityManager: Killing 31844:com.android.externalstorage/u0a100 (adj 0): crash
> ```

DON'T use the Magisk version on Android 14, it's not supported, use the Lsposed version
