### ISSUE TITLE
android 12L issue

### ISSUE THREAD

**Issue by ELKecham** [Magisk-Modules-Alt-Repo/NoStorageRestrict#2]
![Screenshot_20220331-211734_Arquivos](https://user-images.githubusercontent.com/102772308/161170660-505de606-27bd-4a3d-8e07-8670ba842716.png)
![Screenshot_20220331-211615_Arquivos](https://user-images.githubusercontent.com/102772308/161170667-20fe6bf4-8de8-406b-b3cf-c941fb9503fa.png)

The storage is missing when module is instaled
and constant crashes happen

![Screenshot_20220331-211547_Nova Launcher](https://user-images.githubusercontent.com/102772308/161170793-65bc678a-ff28-4fcc-b655-b3c9350cce16.png)

Arrow OS begonia

**Comment by DanGLVK** [comment]
> ![Screenshot_20220331-211734_Arquivos](https://user-images.githubusercontent.com/102772308/161170660-505de606-27bd-4a3d-8e07-8670ba842716.png) ![Screenshot_20220331-211615_Arquivos](https://user-images.githubusercontent.com/102772308/161170667-20fe6bf4-8de8-406b-b3cf-c941fb9503fa.png)
> 
> The storage is missing when module is instaled and constant crashes happen
> 
> ![Screenshot_20220331-211547_Nova Launcher](https://user-images.githubusercontent.com/102772308/161170793-65bc678a-ff28-4fcc-b655-b3c9350cce16.png)
> 
> Arrow OS begonia
[NoStorageRestrict (1).zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/8403657/NoStorageRestrict.1.zip)

Try this zip and see if it works out for you

**Comment by ELKecham** [comment]
Just flashed new version (V2) and the issue got fixed.
