### ISSUE TITLE
Use chmod instead of modified apk

### ISSUE THREAD

**Issue by HuskyDG** [Magisk-Modules-Alt-Repo/NoStorageRestrict#3]
You can make a `late_start` script that will change `/sdcard/Android/*` to `775` every boot by:
```
for user in $(ls /data/media); do
   for i in obb data; do
      chmod -R 775 /data/media/$user/Android/$i
   done
done
```

**Comment by HuskyDG** [comment]
I think it is not enough, might need to do more step for this

**Comment by DanGLES3** [comment]
The issue isn't that of permissions afaik, the storage access framework is artificially restricted by the external storage provider to not allow the selection of the download, Android and root of internal/external storage

**Comment by HuskyDG** [comment]
> The issue isn't that of permissions afaik, the storage access framework is artificially restricted by the external storage provider to not allow the selection of the download, Android and root of internal/external storage
> 
> The only way I've found to bypass that restriction was either by replacing the APK or injecting code through Xposed https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict

I realized that I misunderstood this module
