### ISSUE TITLE
Momo detects Zygisk with this module enabled.

### ISSUE THREAD

**Issue by Nolij** [Magisk-Modules-Alt-Repo/NoStorageRestrict#6]
I've got latest Shamiko, UNSF, Magisk Canary, etc. set up on my phone and with this module Momo is able to detect Zygisk. When I disable it that detection goes away. Perhaps allowing this per-app?

**Comment by DanGLVK** [comment]
> I've got latest Shamiko, UNSF, Magisk Canary, etc. set up on my phone and with this module Momo is able to detect Zygisk. When I disable it that detection goes away. Perhaps allowing this per-app?

That's not something I can do as this module replaces the externalstorageprovider APK with a modded one to work, if you're on a custom ROM you should be able to install the APK inside the module like an app update

**Comment by DanGLVK** [comment]
Alternatively you can now also try the Xposed module that just released

https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict
