### ISSUE TITLE
missing module to download

### ISSUE THREAD

**Issue by egonzalez7579** [Magisk-Modules-Alt-Repo/NoStorageRestrict#9]
I thing the zip module is missing
I am trying to run the module, and tried to use the code / zip and open that on magidisk, but failed to open
and i dont see any other zip file to add to magisk

**Comment by DanGLVK** [comment]
> I thing the zip module is missing I am trying to run the module, and tried to use the code / zip and open that on magidisk, but failed to open and i dont see any other zip file to add to magisk

The modules in the Magisk alt repo are designed to be downloaded through the Fox Module Manager 
https://github.com/Fox2Code/FoxMagiskModuleManager/releases

**Comment by egonzalez7579** [comment]
Thanks
